version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/conf.py

formats: all

python:
  install:
    - path: .
      extra_requirements:
        - xml
        - rdf
    - path: sphinx_rtd_theme
