name: mypy check
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master, dev]

jobs:
  static-type-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - run: pip install mypy
    - name: Type checking and install type stubs for third-party packages
      run: mypy --install-types --non-interactive src

