name: mypy check
on:
  push:
    branches: [main, master, 143-type-hints]
  pull_request:
    branches: [main, master, dev]

jobs:
  static-type-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - run: pip install mypy
    - name: Get Python changed files
      id: changed-py-files
      uses: tj-actions/changed-files@v46
      with:
        files: |
          *.py
          **/*.py
    - name: Run if any of the listed files above is changed
      if: steps.changed-py-files.outputs.any_changed == 'true'
      run: mypy ${{ steps.changed-py-files.outputs.all_changed_files }} --ignore-missing-imports

